export { default as Header } from './components/Header'
export { default as Hero } from './components/Hero'
export { default as NipMarquee } from './components/NipMarquee'
export { default as Features } from './components/Features'
export { default as QuickStart } from './components/QuickStart'
export { default as CtaBand } from './components/CtaBand'
export { default as Footer } from './components/Footer'
export { NIPS, FEATURES } from './data'
export type { Feature } from './data'