micronaut.application.name = 'fenrir-s'

[micronaut.server]
idle-timeout="30s"
#host = "localhost"
port = 6724

[micronaut.router.static-resources.default]
enabled = true
mapping = "/assets/**"
paths = ["classpath:public/assets"]


[micronaut.serde.serialization]
inclusion = "ALWAYS"