GET http://localhost:6724
accept: application/nostr+json

### 1719307113, 1719306274

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"#p":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"]}]

###

WEBSOCKET wss://nostr.wine
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"until": 1719396884,"since":0,"limit": 2}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"since":0,"until": 1719396884}]

###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp", {"#p": ["03742c205cb6c8d86031c93bc4a9b3d18484c32c86563fc0e218910a2df9aa5d"]}]


###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp", {"#p": ["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp", {"#p": ["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"]}]

###

WEBSOCKET wss://nos.lol
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp", {"#p": ["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"]}]


###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"ids":["42224859763652914db53052103f0b744df79dfc4efef7e950fc0802fc3df3c5","2d773becf9fe47623405fa265d83db0fbd91a6148d0bfb72a9471422c2ecd511"]}]

###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[27235]}]


###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"ids":["000000"],"limit":20}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"ids":["d6470ed0c45c73f6ea36bb41011973166af4062a1f3a32f580b5d128f9a60b19"]}]


###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"ids":["b80aa0a2e69e7ca5801a3848aa33e90a62fb30d27284639e1836c9ede8a9d298"]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"ids":["00"]}]


###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"kinds":[40, 41, 42, 43, 44]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[0]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[30002],"limit":50}]

###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[3]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[3]}]

###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[30002],"limit":50}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","KbyQRhDj7o1KLXvZN5nBN",{"kinds":[1985],"#r":["ws://localhost:6724/"],"#l":["review/relay"],"limit":50}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","O-czH3gqfk73WZf6roeTD",{"#a":["30311:c580329df4f1f0dfe35121955ff6636601f780f4184dde206ff33fb50d0b67cb:cf613141-3d2e-4e68-b74e-c5167a79e2a8"],"kinds":[9041]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","6Y92Rj5mPPvkyh9_pYBXD",{"#p":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[1,6,16,7,9735,2004,30023],"limit":150}]
