GET http://localhost:6724
accept: application/nostr+json

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"kinds":[1],"limit":2}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[30002],"limit":50}]


###

WEBSOCKET wss://relay.damus.io
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"authors":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[30002],"limit":50}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","KbyQRhDj7o1KLXvZN5nBN",{"kinds":[1985],"#r":["ws://localhost:6724/"],"#l":["review/relay"],"limit":50}]


###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","O-czH3gqfk73WZf6roeTD",{"#a":["30311:c580329df4f1f0dfe35121955ff6636601f780f4184dde206ff33fb50d0b67cb:cf613141-3d2e-4e68-b74e-c5167a79e2a8"],"kinds":[9041]}]

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","6Y92Rj5mPPvkyh9_pYBXD",{"#p":["e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3"],"kinds":[1,6,16,7,9735,2004,30023],"limit":150}]
