name: Build GraalVM CE Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # * https://github.com/marketplace/actions/docker-compose-with-tests-action?version=v1.5.0
      - name: Build Docker Image
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          up-flags: relay-db  # เรียกใช้ relay-db ซึ่งเป็น service ใน compose.yml

      # * https://github.com/marketplace/actions/github-action-for-graalvm?version=v1.2.5
      - name: Setup GraalVM Environment
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          version: '21.0.2'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify GraalVM
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Update .env Configuration
        run: |
          sed -i 's/#DATABASE_URL=jdbc:postgresql:\/\/localhost:5432/DATABASE_URL=jdbc:postgresql:\/\/localhost:5432/' .env
          sed -i 's/DATABASE_URL=jdbc:postgresql:\/\/relay-db:5432/#DATABASE_URL=jdbc:postgresql:\/\/relay-db:5432/' .env

      - name: Compile Project with GraalVM Native Image
        run: ./gradlew nativeOptimizedCompile

      - name: Check Build Output
        run: |
          if [ -f build/native/nativeOptimizedCompile/fenrir-s-1.0.1-linux-amd64 ]; then
            echo "Build successful!"
          else
            echo "Build failed!"
            exit 1
          fi 
