name: Build JVM 21

on:
  push:
    branches:
      - mod-workflows-nip01
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ขั้นตอนที่ 1: ตรวจสอบโค้ดจาก repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # ขั้นตอนที่ 2: ตั้งค่า Docker Compose สำหรับการทดสอบ
      # * https://github.com/marketplace/actions/docker-compose-with-tests-action?version=v1.5.0
      - name: Build Docker Image
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          up-flags: relay-db

      # ขั้นตอนที่ 3: ติดตั้ง JVM
      # * https://github.com/marketplace/actions/setup-java-jdk?version=v4.5.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: temurin

      # ขั้นตอนที่ 4: ตรวจสอบเวอร์ชันของ JVM
      - name: Verify JVM
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version          

      # ขั้นตอนที่ 5: แก้ไขค่าในไฟล์ .env สำหรับการใช้งาน
      - name: Update .env Configuration
        run: |
          sed -i 's/#DATABASE_URL=jdbc:postgresql:\/\/localhost:5432/DATABASE_URL=jdbc:postgresql:\/\/localhost:5432/' .env
          sed -i 's/DATABASE_URL=jdbc:postgresql:\/\/relay-db:5432/#DATABASE_URL=jdbc:postgresql:\/\/relay-db:5432/' .env

      # ขั้นตอนที่ 6: Compile โค้ด
      - name: Build Project
        run: ./gradlew build -x test

      # ขั้นตอนที่ 7: ตรวจสอบว่าไฟล์ jar ถูกสร้างขึ้นแล้ว
      - name: Check Build Output
        run: |
          if [ -f build/libs/fenrir-s-1.0.1-all-optimized.jar ]; then
            echo "Build successful!"
          else
            echo "Build failed!"
            exit 1
          fi 

      - name: Test WebSocket API
        run: |
          npm install -g wscat
          
          wscat -c ws://localhost:6724/ <<< '["EVENT",{"content":"。　♡ 。　　♡。　　♡ \n♡。　＼　　｜　　／。　♡\n        สวัสดี #siamstr\n♡。　／　　｜　　＼。　♡ \n。　♡。 　　。　　♡","created_at":1742903918,"id":"0000cfad049fa75e0a282090a39fcb1a87de491cd6ebcb4d575967980e3119cc","kind":1,"pubkey":"e4b2c64f0e4e54abb34d5624cd040e05ecc77f0c467cc46e2cc4d5be98abe3e3","sig":"851cf353da085dd73f3248ce811713c247c87900f6eda9af60404d6714e01cebc10b6018ad7bdbd8386584ec757b5bad63445370fc2b214693e526f10f345708","tags":[["t","siamstr"],["nonce","3271","16"]]}]'    
          
          wscat -c ws://localhost:6724/ <<< '["REQ", "sub123", {"kinds":[1]}]'
